# Generated by Django 4.1.5 on 2023-02-06 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("landingpage", "0003_aboutus"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutus",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aboutus",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
