# Generated by Django 4.1.5 on 2023-02-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpage", "0004_aboutus_created_at_aboutus_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutus",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
