# Generated by Django 4.1.5 on 2023-02-06 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landingpage", "0005_alter_aboutus_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutus",
            options={"verbose_name_plural": "About Us"},
        ),
    ]
